spring.application.name=gamingclub
spring.mongodb.uri=mongodb://localhost:27017/gamingclub

# we are working on local machine which uses localhost server
# Mongodb uses 27017 port for running
# gamingclub db will be created